"""v0_5

Revision ID: 14ce4b9a50b1
Revises: 5292d28a2823
Create Date: 2023-12-29 11:07:39.262864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ce4b9a50b1'
down_revision: Union[str, None] = '5292d28a2823'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_request', sa.Column('request_by_user_id', sa.UUID(), nullable=False))
    op.drop_index('ix_follow_request_request_user_id', table_name='follow_request')
    op.create_index(op.f('ix_follow_request_request_by_user_id'), 'follow_request', ['request_by_user_id'], unique=False)
    op.drop_constraint('follow_request_request_user_id_fkey', 'follow_request', type_='foreignkey')
    op.create_foreign_key(None, 'follow_request', 'user', ['request_by_user_id'], ['id'])
    op.drop_column('follow_request', 'request_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follow_request', sa.Column('request_user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'follow_request', type_='foreignkey')
    op.create_foreign_key('follow_request_request_user_id_fkey', 'follow_request', 'user', ['request_user_id'], ['id'])
    op.drop_index(op.f('ix_follow_request_request_by_user_id'), table_name='follow_request')
    op.create_index('ix_follow_request_request_user_id', 'follow_request', ['request_user_id'], unique=False)
    op.drop_column('follow_request', 'request_by_user_id')
    # ### end Alembic commands ###
