"""V0_2

Revision ID: 518cb6aff9b3
Revises: 6f111c00d29a
Create Date: 2023-12-22 11:22:23.021711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '518cb6aff9b3'
down_revision: Union[str, None] = '6f111c00d29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Post_comment_reply',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('comment_reply', sa.String(), nullable=False),
    sa.Column('comment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('reply_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['post_comment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Post_comment_reply_comment_id'), 'Post_comment_reply', ['comment_id'], unique=False)
    op.create_index(op.f('ix_Post_comment_reply_user_id'), 'Post_comment_reply', ['user_id'], unique=False)
    op.add_column('post_comment_like', sa.Column('reply_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_post_comment_like_reply_id'), 'post_comment_like', ['reply_id'], unique=False)
    op.create_foreign_key(None, 'post_comment_like', 'Post_comment_reply', ['reply_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_comment_like', type_='foreignkey')
    op.drop_index(op.f('ix_post_comment_like_reply_id'), table_name='post_comment_like')
    op.drop_column('post_comment_like', 'reply_id')
    op.drop_index(op.f('ix_Post_comment_reply_user_id'), table_name='Post_comment_reply')
    op.drop_index(op.f('ix_Post_comment_reply_comment_id'), table_name='Post_comment_reply')
    op.drop_table('Post_comment_reply')
    # ### end Alembic commands ###
