"""v0_4

Revision ID: 5292d28a2823
Revises: 4e211bc2f98e
Create Date: 2023-12-28 10:37:46.629956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5292d28a2823'
down_revision: Union[str, None] = '4e211bc2f98e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_comment_like', 'reply_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post_comment_like', 'reply_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
